### ISSUE TITLE
feature: improve translations when using variables

### ISSUE THREAD

**Issue by m-overlund** [gaiterjones/magento-buy-x-get-y-free#7]
Would like to suggest a change in the translations in Cartcontroller.php.
Instead of splitting up the translations when using variables, like this:

    $this->__('Your'). ' '. $productYDesc. ' '. $this->__('has been removed from your cart.')

It would be a lot easier to translate by inserting the variables into the sentences, like this:

    $this->__('Your %s has been removed from your cart.', $productYDesc)

Same goes for the translations in csv files:

    "Your","Your"
    "has been removed from your cart.","has been removed from your cart."

Could be a single line instead:

    "Your %s has been removed from your cart.","Your %s has been removed from your cart."

- Will submit a pull request when i get the hang of using git :-)

**Comment by gaiterjones** [comment]
Yes I was a bit lazy here, I will also update the translation strings as you have suggested.

**Comment by m-overlund** [comment]
Great, thank you :-)
